# Generated by Django 4.2.3 on 2023-08-01 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('breed', models.CharField(max_length=50)),
                ('weight', models.IntegerField()),
                ('diet', models.TextField(max_length=250)),
                ('vaccinated', models.BooleanField(default=True)),
            ],
        ),
    ]
