# Generated by Django 4.2.3 on 2023-08-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_reportcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('flavor', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='reportcard',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='dog',
            name='treats',
            field=models.ManyToManyField(to='main_app.treat'),
        ),
    ]
