# Generated by Django 4.2.3 on 2023-08-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_treat_alter_reportcard_options_dog_treats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treat',
            name='flavor',
        ),
        migrations.AlterField(
            model_name='treat',
            name='name',
            field=models.CharField(choices=[('Greenies', 'Greenies'), ('Milk Bones', 'Milk Bones'), ('Beef Bites', 'Beef Bites'), ('Peanut Butter', 'Peanut Butter'), ('String Cheese', 'String Cheese'), ('Blue Berries', 'Blue Berries'), ('Chicken Strips', 'Chicken Strips')], default='Greenies', max_length=100),
        ),
    ]
