# Generated by Django 4.2.3 on 2023-08-01 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_treat_flavor_alter_treat_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treat',
            old_name='name',
            new_name='treat',
        ),
    ]
