# Generated by Django 4.2.3 on 2023-08-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_name_treat_treat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treat',
            name='treat',
        ),
        migrations.AddField(
            model_name='treat',
            name='flavor',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treat',
            name='name',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
    ]
