# Generated by Django 4.2.3 on 2023-08-04 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
