# Generated by Django 4.2.3 on 2023-08-04 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_delete_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treat',
            options={'permissions': [('create_treat', 'Can create treat'), ('remove_treat', 'Can delete treat')]},
        ),
    ]
